### ISSUE TITLE
 response3.headers.all is not a function

### ISSUE THREAD

**Issue by speedingdeer** [mswjs/headers-polyfill#71]
I'm using `msw@0.49.3`

The fresh installation installs `headers-polyfill@3.3.0` through `@mswjs/interceptors`.

I stopped to work for graphql. We receive now this error when calling mocked graqpql endpoint
```
Received: [[GraphQLError: request to http://localhost:9990/api/test failed, reason: response3.headers.all is not a function]]

```

Using `headers-polyfill@3.2.5` resolution works without problem

```
  "resolutions": {
    "headers-polyfill": "3.2.5"
  }
```

**Comment by atsikov** [comment]
It's not clear to my why `headers-polifill@3.3.1` could not be released to restore the behaviour for older mswjs versions.
I spent an hour today trying to figure out why our mswjs-based library which uses `0.47.4` didn't work when installed to a new project however worked fine with all other projects, with tests within the library itself also passing.

**Comment by kettanaito** [comment]
@atsikov, `0.47` is a rather old version of MSW, years old, I believe. I highly encourage you to migrate to 2.0 where this issue is not a thing (we don't rely on `headers-polyfill` anymore).

**Comment by fastndead** [comment]
Hi! I spent a sizeable amount of time debugging this exact bug today so i just wanted to leave this comment for history and maybe make it more googleable

the problem i had is that with upgrading my yarn.lock dependencies my msw tests stoped working. I use `msw v1.1.0` and `yarn v1`. The problem was that even though in yarn.lock it's says that it installed `headers-polyfill` v3.2.5` in reality version in node_modules is `3.3.0` the one with a bug. In combination with the fact that `response3.headers.all is not a function` exception is getting caught and not displayed anywhere it was very frustrating bug to track down. My Axios responses kept just throwing exception `ERR_NETWORK AxiosError` with no further info

hope it helps somebody in the future
